register:
  path: /register
  controller: App\Controller\RegistrationController::register
  methods: POST

api:
  path: /api
  controller: App\Controller\RegistrationController::api

login_check:
  path:     /login_check
  methods:  [POST]
